version: "3.9"

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
     - POSTGRES_USER=prisma
     - POSTGRES_PASSWORD=ignite
     - POSTGRES_DB=prismaTest
     - pgdata:/data/postgres
